from .nodes import (
    KieCrispUpscaleNode,
    KieElevenLabsTTSNode,
    KieGptImage2Node,
    KieGrokImagineI2VNode,
    KieGrokImagineT2INode,
    KieGrokImagineT2VNode,
    KieHappyHorseNode,
    KieHappyHorseR2VNode,
    KieHappyHorseVideoEditNode,
    KieImageLoaderNode,
    KieImagePreviewNode,
    KieKling26VideoNode,
    KieKling30VideoNode,
    KieKlingAiAvatarNode,
    KieNanoBanana2Node,
    KieNanoBananaProNode,
    KieQwen2ImageEditNode,
    KieSeedance2Node,
    KieSeedance15ProNode,
    KieSeedream5LiteNode,
    KieSeedream45Node,
    KieSunoNode,
    KieVeo3Node,
    KieWan22AnimateNode,
    KieWan26Node,
    KieWan27Node,
    KieZImageNode,
    TextNode,
)

NODE_CLASS_MAPPINGS = {
    "KieGptImage2Node": KieGptImage2Node,
    "KieNanoBanana2Node": KieNanoBanana2Node,
    "KieNanoBananaProNode": KieNanoBananaProNode,
    "KieGrokImagineT2INode": KieGrokImagineT2INode,
    "KieGrokImagineI2VNode": KieGrokImagineI2VNode,
    "KieGrokImagineT2VNode": KieGrokImagineT2VNode,
    "KieHappyHorseNode": KieHappyHorseNode,
    "KieHappyHorseR2VNode": KieHappyHorseR2VNode,
    "KieHappyHorseVideoEditNode": KieHappyHorseVideoEditNode,
    "KieCrispUpscaleNode": KieCrispUpscaleNode,
    "KieElevenLabsTTSNode": KieElevenLabsTTSNode,
    "KieZImageNode": KieZImageNode,
    "KieKling26VideoNode": KieKling26VideoNode,
    "KieKling30VideoNode": KieKling30VideoNode,
    "KieKlingAiAvatarNode": KieKlingAiAvatarNode,
    "KieSeedance15ProNode": KieSeedance15ProNode,
    "KieSeedance2Node": KieSeedance2Node,
    "KieQwen2ImageEditNode": KieQwen2ImageEditNode,
    "KieSeedream45Node": KieSeedream45Node,
    "KieSeedream5LiteNode": KieSeedream5LiteNode,
    "KieVeo3Node": KieVeo3Node,
    "KieWan22AnimateNode": KieWan22AnimateNode,
    "KieWan26Node": KieWan26Node,
    "KieWan27Node": KieWan27Node,
    "KieSunoNode": KieSunoNode,
    "KieImagePreviewNode": KieImagePreviewNode,
    "KieImageLoaderNode": KieImageLoaderNode,
    "TextNode": TextNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "TextNode": "Text Node",
    "KieGptImage2Node": "Kie GPT Image 2",
    "KieNanoBanana2Node": "Kie NanoBanana 2",
    "KieNanoBananaProNode": "Kie NanoBanana Pro",
    "KieGrokImagineT2INode": "Kie Grok Imagine (T2I)",
    "KieGrokImagineI2VNode": "Kie Grok Imagine (I2V)",
    "KieGrokImagineT2VNode": "Kie Grok Imagine (T2V)",
    "KieHappyHorseNode": "Kie HappyHorse Video",
    "KieHappyHorseR2VNode": "Kie HappyHorse (R2V)",
    "KieHappyHorseVideoEditNode": "Kie HappyHorse Video Edit",
    "KieCrispUpscaleNode": "Kie Crisp Upscale",
    "KieElevenLabsTTSNode": "Kie ElevenLabs TTS",
    "KieZImageNode": "Kie Z Image",
    "KieKling26VideoNode": "Kie Kling 2.6 Video",
    "KieKling30VideoNode": "Kie Kling 3.0 Video",
    "KieKlingAiAvatarNode": "Kie Kling AI Avatar",
    "KieSeedance15ProNode": "Kie Seedance 1.5 Pro",
    "KieSeedance2Node": "Kie Seedance 2",
    "KieQwen2ImageEditNode": "Kie Qwen2 Image Edit",
    "KieSeedream45Node": "Kie Seedream 4.5",
    "KieSeedream5LiteNode": "Kie Seedream 5 Lite",
    "KieVeo3Node": "Kie Veo 3",
    "KieWan22AnimateNode": "Kie Wan 2.2 Animate",
    "KieWan26Node": "Kie Wan 2.6",
    "KieWan27Node": "Kie Wan 2.7",
    "KieSunoNode": "Kie Suno Music",
    "KieImagePreviewNode": "Kie Image Preview",
    "KieImageLoaderNode": "Kie Image Loader",
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
